---
# transformer
# #prefix_filter: ["he is", "he s ", "she is", "she s "]
# prefix_filter: []
# max_length: 15
# filename: "rus.txt"
# train_size: 0.8
# batch_size: 256

# t5
prefix_filter: []
max_length: 15
filename: "rus.txt"
train_size: 0.8
batch_size: 128
pretrained_tokenizer: 'google-t5/t5-small'